### ISSUE TITLE
find fossil fuel info on little sis

### ISSUE THREAD

**Issue by MargaretBassney** [MargaretBassney/impactlabs_project#8]
- [ ] Investigate current fossil fuel visualizations
- [ ] See what kinds of visualization creation capabilities exist
- [ ] Raw data about fossil fuel lobbying -- what can we use?

Add feedback/notes here: https://docs.google.com/document/d/14JKbfYPhiTgPdsw_beOgNTlySRdK9sz9x7SACFpHpSw/edit

**Comment by Moppit** [comment]
Also, what raw data do they have?
